spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
app:
  env: production
  jwt:
    secret-key: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  url:
    frontend: ${FRONTEND_URL}
  cloudinary:
    cloud_name: ${CLOUDINARY_NAME}
    api_key: ${CLOUDINARY_KEY}
    api_secret: ${CLOUDINARY_SECRET}
